<?php
// :DEVEL BEGIN
function zb_henri_menu() {
    $items['hello'] = array(
        'title' => 'Hello world!',
        'page callback' => 'helloworld_page',
        'access callback' => TRUE,
    );
    return $items;
}
function helloworld_page() {
    echo 'zb_henrisusanto';
}
// :DEVEL END


// :SHIPPING BEGIN
function zb_henri_commerce_shipping_service_info_alter(&$shipping_services) {
    // all active shipping services will use the same policy
    foreach ($shipping_services as $name => $detail){
        $shipping_services[$name]['callbacks']['rate'] = 'zb_henri_zb_shipping_policy';
    }
}
function zb_henri_zb_shipping_policy($shipping_service, $order){
    module_load_include('php', 'zb_henri', '/classes/shipping');
    $shipping = new shipping();
    return $shipping->getShippingPrice($order);
}
// :SHIPPING END


// :SORTING BEGIN
function zb_henri_views_api() {
    return array(
        'api' => 2,
        'path' => drupal_get_path('module', 'zb_henri'),
    );
}
// :SORTING END