<?php

/*
 * DEVELOPMENT PURPOSES
 * @action make sure if module is working
 * PLEASE REMOVE THESE FUNCTIONS
 */
function zb_henri_menu() {
    $items['hello'] = array(
        'title' => 'Hello world!',
        'page callback' => 'helloworld_page',
        'access callback' => TRUE,
    );
    return $items;
}
function helloworld_page() {
    echo 'zb_henrisusanto';
}


/*
 * implement hook_commerce_shipping_service_info_alter
 * @action redirect callback function of any services
 */
function zb_henri_commerce_shipping_service_info_alter(&$shipping_services) {
    foreach ($shipping_services as $name => $detail) {
        $shipping_services[$name]['callbacks']['rate'] = 'zb_henri_zb_shipping_policy';
    }
}

/*
 * Implement Zaner Bloser shipping policy
 * @return calculated shipping rate
 */
function zb_henri_zb_shipping_policy($shipping_service, $order) {
    module_load_include('php', 'zb_henri', '/classes/shipping');
    $shipping = new shipping();
    return $shipping->getShippingPrice($order);
}


/*
 * implement hook_field_create_instance
 * @action update product line and product category sorting field base on product display fields
 *          everytime somebody add a field into product display
 */
function zb_henri_field_create_instance($instance) {
    module_load_include('php', 'zb_henri', '/classes/sorting');
    $sorting = new sorting();
    if ($sorting->product_display['content_type_name'] == $instance['bundle'])
        $sorting->updateSortingOptions();
}

/*
 * implement hook_views_api
 * @action use CUSTOM_MODULE_NAME.views.inc file
 */
function zb_henri_views_api() {
    return array(
        'api' => 2,
        'path' => drupal_get_path('module', 'zb_henri'),
    );
}